name: GUIWarps
version: @version@-@apiversion@
description: GUIWarps
authors: [ DartPower, HunterGaming ]
website: https://github.com/dptmc/GUIWarps
main: io.dpteam.GUIWarps.Main

commands:
  warps:
    usage: /<command>
    description: This command for open warps GUI.